# Meta
env: "development"

title: Mi Sitio Jekyll
description: Un sitio generado con Jekyll
baseurl: "" # Cambia si el sitio no está en el root del dominio
url: "http://localhost:4000" # Dirección de tu sitio

# Build

permalink: pretty
