# Meta
env: "development"

title: Mi Sitio Jekyll
description: Un sitio generado con Jekyll
baseurl: "" # Cambia si el sitio no está en el root del dominio
url: "http://localhost:4000" # Dirección de tu sitio

# Build

permalink: pretty

exclude: 
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _scss
  - package.json
  - package-lock.json
  - buyerjourney.github.io.code-workspace

sass:
  style: compressed
  source_dir: _sass
